Issue12 setup authentication
IchiBizz/IchiBizz pull request #29
Opened 2019-10-06 10:51 UTC by noliko-zwa

-moving passport.js files into config directly some code are moved to app.js
-creating a service directly and  creating a middleware  : client/service/ api.js 
-adding an authentication route : routes/auth.js
-creating a sign up /login/ logout  : client/src/component SignUp.js /Login.js / Logout.js

2019-10-06 11:44 UTC, 1000miles commented
@noliko-zwa Your branch has already a merge conflict. Do you know how to fix it? If not, I can resolve it. Other than that let's try not to merge the 3 PR's today. We most likely will have a few merge conflicts that we should better do together tomorrow.

cc @ninetteadhikari

2019-10-06 11:57 UTC, noliko-zwa commented
I am not sure how to fix it. But i would like to learn if we have time tomorrow and we you don’t mind...!!

> On 6. Oct 2019, at 13:44, Thuy Le <notifications@github.com> wrote:
> 
> @noliko-zwa Your branch has already a merge conflict. Do you know how to fix it? If not, I can resolve it. Other than that let's try not to merge the 3 PR's today. We most likely will have a few merge conflicts that we should better do together tomorrow.
> 
> cc @ninetteadhikari
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-10-06 13:19 UTC, 1000miles commented
> I am not sure how to fix it. But i would like to learn if we have time tomorrow and we you don’t mind...!!
> […](#)
> On 6. Oct 2019, at 13:44, Thuy Le ***@***.***> wrote: @noliko-zwa Your branch has already a merge conflict. Do you know how to fix it? If not, I can resolve it. Other than that let's try not to merge the 3 PR's today. We most likely will have a few merge conflicts that we should better do together tomorrow. cc @ninetteadhikari — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

sure, let's practice git merges tomorow. it will be a good practice for us all. :)

2019-10-07 20:58 UTC, ninetteadhikari reviewed
Looks good to me :)

2019-10-08 11:13 UTC, 1000miles requested changes
@noliko-zwa Great job so far, thanks a lot. 

Can you please check the validation functions based on `username`, `email` and `password` mistakes/empty input fields that are required or have other rules? For better usability we need to display the flash messages/error messages to the user. Thank you.

2019-10-08 11:13 UTC, 1000miles commented on client/src/App.js
> +import Contact from "./components/Contact";
Please remove or comment out this part for the `Contact` component since this is a separate task.

2019-10-08 11:13 UTC, 1000miles commented on client/src/App.js
> +        <Route exact path="/contact" component={Contact} />
Please remove or comment out this part for the `Contact` component since this is a separate task.

2019-10-08 11:13 UTC, 1000miles commented on client/src/components/Contact.js
> +}
Please remove or comment out this part for the `Contact` component since this is a separate task.

2019-10-08 11:13 UTC, 1000miles commented on client/src/components/Login.js
> +    username: "",
Please remove `username` if we don't use it for login.

2019-10-08 11:13 UTC, 1000miles commented on client/src/components/Logout.js
> +        this.props.history.push("/projects");
This should be changed to `/products`. :D

2019-10-08 11:13 UTC, 1000miles commented on client/src/components/SignUp.js
> +            label="password / min. 8char"
Do we have a validation check here with min. 8 char?

2019-10-08 11:13 UTC, 1000miles commented on client/src/index.js
> +
Do you mind to remove empty lines here? It was probably `prettier`?

2019-10-08 11:13 UTC, 1000miles commented on client/src/index.js
> +
Same as above, please remove empty line changes.

2019-10-08 13:54 UTC, 1000miles requested changes
@noliko-zwa The validations need to be improved. 

At the moment I get confusing behaviors.

1. If email is invalid (missing or email format invalid), please don't allow to progress and provide an error message
2. If password is missing or smaller than 8, please don't allow to signup and provide an error message. at the moment I get a success message if I provide only 2 characters.
3. Please put the error messages in red for better readability.

![Screenshot 2019-10-08 at 15 47 55](https://user-images.githubusercontent.com/4077916/66401701-e2987100-e9e3-11e9-9c2e-436ede3181f5.jpg)
![Screenshot 2019-10-08 at 15 47 32](https://user-images.githubusercontent.com/4077916/66401716-e88e5200-e9e3-11e9-87be-e146bae74f1f.jpg)

2019-10-08 16:54 UTC, 1000miles commented
@noliko-zwa Can you please fix the conflict in this PR?

2019-10-09 13:28 UTC, ninetteadhikari approved these changes
This is working for me ⭐️ 🌮

2019-10-09 13:29 UTC, merged